# CFLAGS_tracepoints.o := -I$(src)
obj-$(CONFIG_SEPEXTRACTTRACER) += sepextract.o
sepextract-objs := ccnt_usr.o sepext.o sepext_trace.o globals.o static.o dynamic.o st.o pktextractors.o tracepoints.o

